#on:
#  push:
#    tags:
#      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
on: [push]

name: Build and push docker

jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build docker
        run: docker build -f Dockerfile.base -t docker.pkg.github.com/lindell/label-commenter/main:latest .

      - name: Push the image to GPR
        run: |
          docker login docker.pkg.github.com -u publisher -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
          docker push docker.pkg.github.com/lindell/label-commenter/main:latest
        env:
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
