name: A workflow for my Hello World file
on: issues
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            not reproducible:
              text: |
                Hi and thanks for creating this issue.
                Unfortunately, the information you have provided is not enough to reproduce the error you have stated.
                Please provide more information and this issue will hopefully be solved.
              ignore-previous: true
